(setq elfeed-feeds (quote (
                           ;; "http://www.hellfest.fr/web08/locale/french/rss.xml"
                           "http://feeds.feedburner.com/mairie13"
                           "http://www.mountyhall.com/ScriptPublic/MH_News.xml"
                           "http://www.ccc.de/de/rss/updates.rdf"
                           ;; "http://www.cafzone.net/ipb/index.php?act=rssout&id=1"
                           "http://news.ycombinator.com/rss"
                           ;; "http://www.siteduzero.com/Templates/xml/news_fr.xml"
                           "http://aperiodic.net/phil/archives/index.rss"
                           "http://formats-ouverts.org/rss.php"
                           "http://feeds.feedburner.com/RogerAlsingWeblog"
                           "http://rss.slashdot.org/Slashdot/slashdot"
                           "http://feeds.feedburner.com/tedtalks_video"
                           ;; "http://pisani.blog.lemonde.fr/pisani/index.rdf"
                           "http://www.acrimed.org/spip.php?page=backend"
                           "http://www.marianne2.fr/xml/syndication.rss"
                           ;; "http://blogs.rtl.fr/usa/index.php/feed/rss2"
                           "http://www.stallman.org/rss/rss.xml"
                           "http://feeds.feedburner.com/refletsinfo"
                           ;; "http://www.ujfp.org/backend.php/"
                           "http://feeds.feedburner.com/bashfr"
                           "http://www.geeek.org/feed/tag/geek/rss2"
                           "http://feeds2.feedburner.com/BonjourMadame"
                           "http://www.dafuckingblueboy.com/?feed=rss2"
                           "http://maruk-and-slash.blogspot.com/feeds/posts/default?alt=rss"
                           "http://www.labanane.org/humourabsurde.xml"
                           "http://www.labanane.org/humourdouteux.xml"
                           "http://www.labanane.org/humourgras.xml"
                           "http://www.labanane.org/humournoir.xml"
                           "http://lelombrik.net/news.rss"
                           "http://www.monpirecoup.fr/index/rss"
                           "http://motivateurself.wordpress.com/feed/"
                           "http://syndication.thedailywtf.com/TheDailyWtf"
                           "http://blog.zanorg.com/rss/fil_rss.xml"
                           ;; "http://www.30joursdebd.com/mag/rss.php"
                           "http://abstrusegoose.com/feed"
                           "http://accroche-toi-a-ton-sloup.over-blog.com/atom.php"
                           ;; "http://crea.bib.free.fr/blog/rss.php"
                           "http://www.fabricetarrin.com/blog/rss.php"
                           ;; "http://www.bouletcorp.com/blog/fill_rss.php5"
                           "http://feeds.feedburner.com/bouletcorpen"
                           "http://bowwindow.canalblog.com/rss.xml"
                           "http://feeds.feedburner.com/Buttersafe"
                           "http://wdr1.com/blog/calvin_and_hobbes.rdf"
                           ;; "http://chezunter.free.fr/barblug/rss.php"
                           "http://www.chicou-chicou.com/rss/fil_rss.xml"
                           "http://feeds.feedburner.com/CommeDesGuilisDansLeBasDuVentre?format=xml"
                           "http://feeds.feedburner.com/Croustination"
                           ;; "http://delfineblog.free.fr/blog/?feed=rss2"
                           ;; "http://www.caesar.nl/CaesarRSS/DilbertRSS.aspx"
                           "http://feeds.dilbert.com/DilbertDailyStrip"
                           "http://feeds2.feedburner.com/thedoghousediaries/feed"
                           "http://www.duelinganalogs.com/feed/"
                           "http://ptitenezu.blogspot.com/feeds/posts/default"
                           "http://feeds.feedburner.com/Explosm"
                           ;; "http://filsdelacolere.com/rss.php"
                           "http://fernandlours.free.fr/rss.php"
                           "http://feeds.feedburner.com/Pidjin"
                           "http://gallybox.com/blog/feed/"
                           "http://feeds.feedburner.com/GeekAndPoke"
                           "http://www.nojhan.net/geekscottes/rss.php"
                           "http://beyondzedoodles.blogspot.com/atom.xml"
                           "http://jimmybeaulieu.com/feed/"
                           ;; "http://www.johnandjohn.nl/rss.php"
                           "http://blogdejulienneel.blogspot.com/feeds/posts/default"
                           "http://www.jeromeuh.net/index.xml"
                           "http://feeds.feedburner.com/labandepasdessinee"
                           "http://maesterbd.wordpress.com/feed/"
                           "http://lanternebrisee.net/feed/rss2"
                           "http://jap-jap-jap-jap.blogspot.com/feeds/posts/default"
                           "http://vidberg.blog.lemonde.fr/feed/"
                           ;; "http://www.lapin.org/fluxrss.xml"
                           ;; "http://avosrisquesetperils.blogspot.com/feeds/posts/default"
                           "http://ceduniverse.blogspot.com/atom.xml"
                           ;; "http://missgally.com/blog/rss.php"
                           ;; "http://lindingre.com/?feed=rss2"
                           "http://yap-yap-yap-yap.blogspot.com/feeds/posts/default?alt=rss"
                           "http://puccafun.canalblog.com/rss.xml"
                           "http://www.fortuworld.com/blog/rss/fil_rss.xml"
                           "http://journaldecamille.blogspot.com/feeds/posts/default"
                           "http://pleindhistoires.canalblog.com/rss.xml"
                           "http://www.maliki.com/rss.xml"
                           ;; "http://www.allanbarte.com/blog/rss.php"
                           "http://maester.over-blog.com/rss2.php"
                           "http://www.lesbobodessins.fr/feed"
                           "http://marnette.canalblog.com/rss.xml"
                           "http://feeds.feedburner.com/BlogPenelopeJolicoeur"
                           "http://blog.chabd.com/abonnement.xml"
                           "http://mamlynda.blogspot.com/feeds/posts/default?alt=rss"
                           "http://maneggs.com/feed/rss/"
                           ;; "http://www.melakarnets.com/rss.php"
                           "http://deligne.over-blog.com/rss-articles.xml"
                           ;; "http://rss.monbeausapin.org/MonBeauSapin"
                           "http://www.monsieur-le-chien.fr/rss.php"
                           ;; "http://madeofstorm.free.fr/myheadupsidedown/?feed=rss2"
                           "http://www.penelope-jolicoeur.com/feed/"
                           "http://grumeautique.blogspot.com/feeds/posts/default"
                           "http://www.phdcomics.com/gradfeed.php"
                           "http://www.smbc-comics.com/rss.php"
                           "http://theoatmeal.com/feed/rss"
                           "http://placeman.canalblog.com/rss.xml"
                           "http://tumourrasmoinsbete.blogspot.com/feeds/posts/default"
                           ;; "http://wandrille.leroy.free.fr/blog/rss.php"
                           "http://what-if.xkcd.com/feed.atom"
                           "http://www.xkcd.com/rss.xml"
                           "http://feeds2.feedburner.com/yehudamoon"
                           "http://www.yodablog.net/?feed=rss2"
                           "http://atravers.blogspot.com/feeds/posts/default"
                           ;; "http://linuxfr.org/backend/news-homepage/rss20.rss"
                           ;; "http://www.generation-libre.com/index2.php?option=com_rss&feed=RSS2.0&no_html=1"
                           ;; "http://www.invox.org/backend.php3"
                           ;; "http://www.linuxpourlesnuls.org/backend.php"
                           ;; "http://www.nuxo.net/rss.php"
                           ;; "http://www.pointblog.com/index.rdf"
                           "http://www.unixtech.be/?feed=atom"
                           "http://feeds.feedburner.com/AbhijeetMaharana"
                           "http://www.dotnetguru2.org/xmlsrv/rss2.php?blog=35"
                           "http://fabien.bezagu.free.fr/rss.php"
                           "http://www.gravedingo.com/feed"
                           ;; "http://i.got.nothing.to/feed/atom"
                           ;; "http://feeds.feedburner.com/jackslocum"
                           "http://maitre-eolas.fr/rss.php"
                           "http://www.korben.info/feed"
                           "http://drorlof.blogspot.com/feeds/posts/default?alt=rss"
                           ;; "http://penseesderonde.mabulle.com/rss.php"
                           "http://onsefechier-anatic6.blogspot.com/feeds/posts/default"
                           "http://partipirate.org/blogs/maxime-rouquet/feed/"
                           "http://www.superno.com/blog/feed/"
                           "http://mnouchkine.blogs.liberation.fr/le_fil_da/index.rdf"
                           "http://feeds.feedburner.com/GeekPauvre"
                           "http://misko.hevery.com/feed/"
                           "http://blog.morpheuz.cc/feed/"
                           ;; "http://www.nicollet.net/feed/"
                           "http://www.ripton.net/blog/?feed=atom"
                           "http://petrole.blog.lemonde.fr/feed/"
                           "http://merome.net/dotclear/rss.php"
                           "http://purefuckingarmageddon.blogspot.com/feeds/posts/default"
                           "http://blog.romainriviere.fr/feed/"
                           "http://www.jroller.com/sjivan/feed/entries/rss"
                           "http://feeds.feedburner.com/schneier/fulltext"
                           "http://www.aubryconseil.com/feed/rss2"
                           "http://sebsauvage.net/rhaa/rss_fulltext.php"
                           ;; "http://feeds.feedburner.com/tlb-articles"
                           "http://feeds.feedburner.com/thehappyseeker"
                           "http://feeds.feedburner.com/thuss"
                           ;; "http://feeds.feedburner.com/torrefaction"
                           "http://blog.tristramg.eu/feeds/all.atom.xml"
                           ;; "http://tristramg.info/wiki/feed.php"
                           ;; "http://evesanctuary.free.fr/dotclear2/blog/feed/atom"
                           "http://adriensaumier.fr/index.php?feed/atom"
                           "http://zenhabits.net/feed/"
                           "http://www.application-servers.com/feed/rss2"
                           ;; "http://www.application-servers.com/rss/appservers.rss"
                           "http://feeds.feedburner.com/BirtWorld"
                           "http://blog.objetdirect.com/feed"
                           "http://feeds.codecommit.com/codecommit"
                           ;; "http://www.eclipse-plugins.info/eclipse/plugins_backend.jsp?what=newandupdated"
                           "http://gmailblog.blogspot.com/atom.xml"
                           "http://feeds.feedburner.com/gtricksrss"
                           "http://www.insideit.fr/feed/rss2"
                           "http://www.insideit.fr/feed/rss2/comments"
                           "http://www.lamoooche.com/getRSS.php?idnews=32"
                           "http://www.dng-consulting.com/blogs/index.php?blog=1&tempskin=_rss2"
                           "http://www.touilleur-express.fr/feed/"
                           "http://blog.netapsys.fr/index.php/feed/rss2"
                           "http://googlereader.blogspot.com/atom.xml"
                           ;; "http://www.ongwt.com/feed/rss2"
                           "http://feeds.feedburner.com/threeriversinstitute/khkV"
                           "http://nullprogram.com/feed/"
                           )))
