;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-delete-forward
        kill-region
        org-backward-sentence
        org-delete-char
        org-kill-line
        org-self-insert-command
        ))

(setq mc/cmds-to-run-once
      '(
        apropos-documentation
        kmacro-start-macro
        org-beginning-of-line
        org-end-of-line
        ))
